apiVersion: v1
kind: Service
metadata:
  labels:
    service: grpc-persons
  name: grpc-persons
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
    nodePort: 30006
  selector:
    service: grpc-persons
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: grpc-persons
  name: grpc-persons
spec:
  replicas: 1
  selector:
    matchLabels:
      service: grpc-persons
  template:
    metadata:
      labels:
        service: grpc-persons
    spec:
      containers:
      - image: barhome/grpc-persons:latest
        name: grpc-persons
        imagePullPolicy: Always
      restartPolicy: Always
