openapi: 3.0.0
info:
  title: API for locations
  description: Obtain Locations
  version: latest
servers:
  -  description: Location API for udaconnect project
     url: http://localhost:30003/
paths:
  /api-locations/locations/{location_id}:
    get:
      summary: Retrieve a location
      description: Retrive location filtered by location id
      operationId: retreive
      parameters:
        - name: location_id
          in: path
          description: location_id - Unique ID for a given Location
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/location'
   
  /api-locations/locations:
    post:
      summary: Create one location 
      description: Create one location.
      operationId: create
      responses:
        '202':
          description: successfully added a location
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/location'
        required: true
    get:
      summary: retreive all locations
      description: retrieve all  locations.
      operationId: retrieveall
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/location'
         

components:
  schemas:
    location:
      type: object
      properties:
        id:
          type: integer
        person_id:
          type: integer
        coordinates:
          type: object
          properties:
            logatitude:
              type: string
            altitude:
              type: string
        Creation_time:
          type: string
          format: time
