name: "udaconnect project 2 - Package with Docker"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/frontend
          file: ./modules/frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: cchla1021/udaconnect-frontend:latest
          
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/api-persons
          file: ./modules/api-persons/Dockerfile
          platforms: linux/amd64
          push: true
          tags: cchla1021/api-persons:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/api-connection
          file: ./modules/api-connection/Dockerfile
          platforms: linux/amd64
          push: true
          tags: cchla1021/api-connection:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/api-locations-producer
          file: ./modules/api-locations-producer/Dockerfile
          platforms: linux/amd64
          push: true
          tags: cchla1021@api-locations-producer:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./modules/api-locations-consumer
          file: ./modules/api-locations-consumer/Dockerfile
          platforms: linux/amd64
          push: true
          tags: cchla1021@api-locations-consumer:latest
